package com.nextgen.courtvision.ui.login

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.view.isVisible
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.material.snackbar.Snackbar
import com.nextgen.courtvision.CourtVisionApp
import com.nextgen.courtvision.R
import com.nextgen.courtvision.databinding.FragmentLoginBinding
import com.nextgen.courtvision.viewmodel.AuthUiState
import com.nextgen.courtvision.viewmodel.AuthViewModel
import kotlinx.coroutines.launch

class LoginFragment : Fragment() {

    private var _binding: FragmentLoginBinding? = null
    private val binding get() = _binding!!

    private val authViewModel: AuthViewModel by activityViewModels {
        AuthViewModel.Factory(
            (requireActivity().application as CourtVisionApp).container.authRepository,
        )
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        _binding = FragmentLoginBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        binding.buttonSignIn.setOnClickListener {
            authViewModel.signIn(
                binding.inputEmail.text?.toString().orEmpty(),
                binding.inputPassword.text?.toString().orEmpty(),
            )
        }
        binding.buttonGoogle.setOnClickListener { startGoogleSignIn() }
        binding.linkRegister.setOnClickListener {
            findNavController().navigate(R.id.registerFragment)
        }

        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                authViewModel.uiState.collect { state ->
                    binding.progress.isVisible = state is AuthUiState.Loading
                    binding.buttonSignIn.isEnabled = state !is AuthUiState.Loading
                    binding.buttonGoogle.isEnabled = state !is AuthUiState.Loading
                    if (state is AuthUiState.Error) {
                        Snackbar.make(binding.root, state.message, Snackbar.LENGTH_LONG).show()
                        authViewModel.acknowledgeError()
                    }
                }
            }
        }
    }

    private fun startGoogleSignIn() {
        // default_web_client_id is generated by the google-services plugin; looked
        // up dynamically so the app still compiles before Firebase is configured.
        val clientIdRes = resources.getIdentifier(
            "default_web_client_id", "string", requireContext().packageName,
        )
        if (clientIdRes == 0) {
            Snackbar.make(
                binding.root,
                getString(R.string.error_google_not_configured),
                Snackbar.LENGTH_LONG,
            ).show()
            return
        }

        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(getString(clientIdRes))
            .setFilterByAuthorizedAccounts(false)
            .build()
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        viewLifecycleOwner.lifecycleScope.launch {
            try {
                val response = CredentialManager.create(requireContext())
                    .getCredential(requireContext(), request)
                val credential = response.credential
                if (credential is CustomCredential &&
                    credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                ) {
                    val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
                    authViewModel.signInWithGoogle(idToken)
                }
            } catch (_: GetCredentialCancellationException) {
                // User dismissed the account picker — not an error.
            } catch (e: GetCredentialException) {
                Snackbar.make(
                    binding.root,
                    e.message ?: getString(R.string.error_google_sign_in),
                    Snackbar.LENGTH_LONG,
                ).show()
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
